const crypto=require('crypto');
const zlib=require('zlib');
const id=p=>p+'-'+crypto.randomBytes(5).toString('hex').toUpperCase();
const clean=s=>String(s??'').trim().slice(0,5000);
const money=v=>{const n=Number(v);return Number.isFinite(n)&&n>=0?n:0};
function init(db){
 const keys=['deliveries','deliveryEvents','portalAccounts','portalMessages','mobileDevices','mobileSyncLogs','executiveSnapshots','reportRuns'];
 for(const k of keys)if(!Array.isArray(db[k]))db[k]=[];
}
function auth(req){return !!req._rbsSession}
function totals(db){
 const sales=db.sales||[], expenses=db.expenses||[], cash=db.cashMovements||[];
 const revenue=sales.reduce((n,x)=>n+money(x.total),0), expense=expenses.reduce((n,x)=>n+money(x.amount),0);
 const cashIn=cash.filter(x=>x.type==='Entrada').reduce((n,x)=>n+money(x.amount),0), cashOut=cash.filter(x=>x.type==='Saída').reduce((n,x)=>n+money(x.amount),0);
 const stock=(db.products||[]).reduce((n,x)=>n+money(x.stock)*money(String(x.price||'').replace(/[^0-9.,]/g,'').replace(',','.')),0);
 return {revenue,expense,result:revenue-expense,cashIn,cashOut,cashBalance:cashIn-cashOut,stockValue:stock,customers:(db.customers||[]).length,products:(db.products||[]).length,employees:(db.employees||[]).filter(x=>x.status==='Ativo').length,deliveries:(db.deliveries||[]).length,projects:(db.projects||[]).length,services:(db.serviceOrders||[]).length};
}
function csv(rows){if(!rows.length)return 'sep=,\n';const cols=[...new Set(rows.flatMap(r=>Object.keys(r)))];const esc=v=>'"'+String(v??'').replace(/"/g,'""')+'"';return '\ufeff'+cols.map(esc).join(',')+'\n'+rows.map(r=>cols.map(c=>esc(r[c])).join(',')).join('\n');}
function pdf(text){
 const safe=String(text).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
 const lines=safe.split(/\r?\n/).slice(0,45); let stream='BT\n/F1 10 Tf\n40 800 Td\n';
 lines.forEach((l,i)=>{if(i)stream+='0 -16 Td\n';stream+='('+l.slice(0,110)+') Tj\n';});stream+='ET';
 const objs=[];objs.push('<< /Type /Catalog /Pages 2 0 R >>');objs.push('<< /Type /Pages /Kids [3 0 R] /Count 1 >>');objs.push('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>');objs.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');objs.push(`<< /Length ${Buffer.byteLength(stream,'latin1')} >>\nstream\n${stream}\nendstream`);
 let out='%PDF-1.4\n',offs=[0];for(let i=0;i<objs.length;i++){offs.push(Buffer.byteLength(out,'latin1'));out+=(i+1)+' 0 obj\n'+objs[i]+'\nendobj\n';}const xref=Buffer.byteLength(out,'latin1');out+='xref\n0 '+(objs.length+1)+'\n0000000000 65535 f \n';for(let i=1;i<offs.length;i++)out+=String(offs[i]).padStart(10,'0')+' 00000 n \n';out+='trailer\n<< /Size '+(objs.length+1)+' /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF';return Buffer.from(out,'latin1');
}
function zipStore(files){
 const crc32=buf=>{let c=~0;for(const b of buf){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xEDB88320:0)}return (~c)>>>0};
 const parts=[],central=[];let off=0;
 for(const [name,data] of Object.entries(files)){const n=Buffer.from(name),d=Buffer.isBuffer(data)?data:Buffer.from(data);const c=crc32(d);const h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50,0);h.writeUInt16LE(20,4);h.writeUInt16LE(0,6);h.writeUInt16LE(0,8);h.writeUInt16LE(0,10);h.writeUInt16LE(0,12);h.writeUInt32LE(c,14);h.writeUInt32LE(d.length,18);h.writeUInt32LE(d.length,22);h.writeUInt16LE(n.length,26);h.writeUInt16LE(0,28);parts.push(h,n,d);const ch=Buffer.alloc(46);ch.writeUInt32LE(0x02014b50,0);ch.writeUInt16LE(20,4);ch.writeUInt16LE(20,6);ch.writeUInt16LE(0,8);ch.writeUInt16LE(0,10);ch.writeUInt16LE(0,12);ch.writeUInt16LE(0,14);ch.writeUInt32LE(c,16);ch.writeUInt32LE(d.length,20);ch.writeUInt32LE(d.length,24);ch.writeUInt16LE(n.length,28);ch.writeUInt16LE(0,30);ch.writeUInt16LE(0,32);ch.writeUInt16LE(0,34);ch.writeUInt16LE(0,36);ch.writeUInt32LE(0,38);ch.writeUInt32LE(off,42);central.push(ch,n);off+=h.length+n.length+d.length;}
 const cd=Buffer.concat(central), body=Buffer.concat(parts);const e=Buffer.alloc(22);e.writeUInt32LE(0x06054b50,0);e.writeUInt16LE(8,8);e.writeUInt16LE(8,10);e.writeUInt32LE(Object.keys(files).length,8);e.writeUInt32LE(Object.keys(files).length,10);e.writeUInt32LE(cd.length,12);e.writeUInt32LE(body.length,16);return Buffer.concat([body,cd,e]);
}
async function handle(req,res,ctx){
 const {db,save,json,body,session}=ctx;req._rbsSession=session(req);if(!auth(req))return false;
 const p=new URL(req.url,'http://localhost').pathname;
 // V26 Delivery
 if(req.method==='GET'&&p==='/api/v26/delivery/summary')return json(res,200,{deliveries:db.deliveries.length,pending:db.deliveries.filter(x=>!['Entregue','Cancelada'].includes(x.status)).length,delivered:db.deliveries.filter(x=>x.status==='Entregue').length,fees:db.deliveries.reduce((n,x)=>n+money(x.fee),0)});
 if(req.method==='POST'&&p==='/api/v26/deliveries'){const b=await body(req);if(!clean(b.customerId)||!clean(b.address))return json(res,400,{error:'Cliente e endereço são obrigatórios'});const x={id:id('DEL'),number:'DEL/'+new Date().getFullYear()+'/'+String(db.deliveries.length+1).padStart(5,'0'),customerId:clean(b.customerId),orderId:clean(b.orderId),address:clean(b.address),phone:clean(b.phone),driver:clean(b.driver),areaCode:clean(b.areaCode),fee:money(b.fee),status:clean(b.status)||'Pendente',scheduledDate:clean(b.scheduledDate),notes:clean(b.notes),createdAt:new Date().toISOString()};db.deliveries.unshift(x);db.deliveryEvents.unshift({id:id('DEV'),deliveryId:x.id,status:x.status,note:'Entrega criada',createdAt:x.createdAt});save();return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/v26/deliveries')return json(res,200,db.deliveries);
 if(req.method==='PUT'&&p.startsWith('/api/v26/deliveries/')){const x=db.deliveries.find(q=>q.id===decodeURIComponent(p.split('/').pop()));if(!x)return json(res,404,{error:'Entrega não encontrada'});const b=await body(req),valid=['Pendente','Agendada','Em trânsito','Entregue','Cancelada'];if(b.status&&!valid.includes(b.status))return json(res,400,{error:'Estado inválido'});if(b.status){x.status=b.status;db.deliveryEvents.unshift({id:id('DEV'),deliveryId:x.id,status:x.status,note:clean(b.note),createdAt:new Date().toISOString()})}for(const f of ['driver','scheduledDate','address','phone','notes'])if(b[f]!==undefined)x[f]=clean(b[f]);save();return json(res,200,x)}
 if(req.method==='GET'&&p.startsWith('/api/v26/deliveries/')&&p.endsWith('/events')){const k=p.split('/')[4];return json(res,200,db.deliveryEvents.filter(x=>x.deliveryId===k))}
 // V27 Customer portal
 if(req.method==='GET'&&p==='/api/v27/portal/summary')return json(res,200,{accounts:db.portalAccounts.length,active:db.portalAccounts.filter(x=>x.active).length,messages:db.portalMessages.length});
 if(req.method==='POST'&&p==='/api/v27/portal/accounts'){const b=await body(req);if(!clean(b.customerId)||!clean(b.username))return json(res,400,{error:'Cliente e utilizador são obrigatórios'});if(db.portalAccounts.some(x=>x.username===clean(b.username)))return json(res,409,{error:'Utilizador do portal já existe'});const x={id:id('PAC'),customerId:clean(b.customerId),username:clean(b.username),active:true,createdAt:new Date().toISOString()};db.portalAccounts.unshift(x);save();return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/v27/portal/accounts')return json(res,200,db.portalAccounts);
 if(req.method==='GET'&&p==='/api/v27/portal/customer/')return json(res,400,{error:'Informe o ID do cliente'});
 if(req.method==='GET'&&p.startsWith('/api/v27/portal/customer/')){const cid=decodeURIComponent(p.split('/').pop()),customer=(db.customers||[]).find(x=>x.id===cid);if(!customer)return json(res,404,{error:'Cliente não encontrado'});return json(res,200,{customer,orders:(db.orders||[]).filter(x=>x.customerId===cid||x.phone===customer.phone),quotes:(db.quotes||[]).filter(x=>x.customerId===cid),deliveries:db.deliveries.filter(x=>x.customerId===cid),services:db.serviceOrders.filter(x=>x.customerId===cid),messages:db.portalMessages.filter(x=>x.customerId===cid)})}
 if(req.method==='POST'&&p==='/api/v27/portal/messages'){const b=await body(req);if(!clean(b.customerId)||!clean(b.message))return json(res,400,{error:'Cliente e mensagem são obrigatórios'});const x={id:id('PMSG'),customerId:clean(b.customerId),subject:clean(b.subject),message:clean(b.message),status:'Aberta',createdAt:new Date().toISOString()};db.portalMessages.unshift(x);save();return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/v27/portal/messages')return json(res,200,db.portalMessages);
 // V28 Android/mobile API foundation
 if(req.method==='GET'&&p==='/api/v28/mobile/config')return json(res,200,{appName:'RBS Gestão',version:'28.0.0',apiVersion:'v28',currency:'Kz',offlineReady:true,syncSupported:true});
 if(req.method==='POST'&&p==='/api/v28/mobile/devices'){const b=await body(req);if(!clean(b.deviceId)||!clean(b.platform))return json(res,400,{error:'deviceId e platform são obrigatórios'});let x=db.mobileDevices.find(q=>q.deviceId===clean(b.deviceId));if(x)Object.assign(x,{platform:clean(b.platform),appVersion:clean(b.appVersion),lastSeen:new Date().toISOString()});else{x={id:id('DEV'),deviceId:clean(b.deviceId),platform:clean(b.platform),appVersion:clean(b.appVersion),lastSeen:new Date().toISOString(),createdAt:new Date().toISOString()};db.mobileDevices.unshift(x)}save();return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/v28/mobile/sync'){const since=clean(new URL(req.url,'http://localhost').searchParams.get('since'));const stamp=since?Date.parse(since):0;const changed=(db.products||[]).filter(x=>Date.parse(x.updatedAt||x.createdAt||0)>stamp);return json(res,200,{serverTime:new Date().toISOString(),products:changed,customers:(db.customers||[]).filter(x=>Date.parse(x.updatedAt||x.createdAt||0)>stamp),deliveries:db.deliveries.filter(x=>Date.parse(x.updatedAt||x.createdAt||0)>stamp)});}
 if(req.method==='POST'&&p==='/api/v28/mobile/sync-log'){const b=await body(req);const x={id:id('SYNC'),deviceId:clean(b.deviceId),direction:clean(b.direction)||'pull',items:money(b.items),createdAt:new Date().toISOString()};db.mobileSyncLogs.unshift(x);save();return json(res,201,x)}
 // V29 Executive dashboard
 if(req.method==='GET'&&p==='/api/v29/executive/summary'){const t=totals(db),crm=db.crmDeals||[],areas=db.areaEntries||[],areaExp=db.areaExpenses||[],hr=db.employees||[];const pipeline=crm.reduce((n,x)=>n+money(x.value),0);const ar={};for(const x of areas)ar[x.areaCode]=(ar[x.areaCode]||0)+money(x.amount);for(const x of areaExp)ar[x.areaCode]=(ar[x.areaCode]||0)-money(x.amount);return json(res,200,{generatedAt:new Date().toISOString(),totals:t,crm:{deals:crm.length,pipeline},areas:ar,hr:{employees:hr.length,active:hr.filter(x=>x.status==='Ativo').length},operations:{deliveries:db.deliveries.length,projects:db.projects.length,services:db.serviceOrders.length}})}
 if(req.method==='POST'&&p==='/api/v29/executive/snapshots'){const s={id:id('SNAP'),createdAt:new Date().toISOString(),data:totals(db)};db.executiveSnapshots.unshift(s);save();return json(res,201,s)}
 if(req.method==='GET'&&p==='/api/v29/executive/snapshots')return json(res,200,db.executiveSnapshots);
 // V30 Reports and exports
 if(req.method==='GET'&&p==='/api/v30/reports/summary'){const t=totals(db);return json(res,200,{generatedAt:new Date().toISOString(),totals:t,available:['csv','xlsx','pdf']})}
 if(req.method==='GET'&&p==='/api/v30/reports/export'){const q=new URL(req.url,'http://localhost').searchParams,format=(q.get('format')||'csv').toLowerCase();const t=totals(db),rows=Object.entries(t).map(([metric,value])=>({metric,value}));if(format==='csv'){res.writeHead(200,{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="rbs-relatorio-v30.csv"'});res.end(csv(rows));return true}if(format==='pdf'){res.writeHead(200,{'Content-Type':'application/pdf','Content-Disposition':'attachment; filename="rbs-relatorio-v30.pdf"'});res.end(pdf('RBS — Relatório Executivo V30\nGerado: '+new Date().toISOString()+'\n\n'+rows.map(x=>x.metric+': '+x.value).join('\n')));return true}if(format==='xlsx'){const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');const sheet='<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'+rows.map((r,i)=>`<row r="${i+1}"><c r="A${i+1}" t="inlineStr"><is><t>${esc(r.metric)}</t></is></c><c r="B${i+1}"><v>${Number(r.value)||0}</v></c></row>`).join('')+'</sheetData></worksheet>';const files={'[Content_Types].xml':'<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>','_rels/.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>','xl/workbook.xml':'<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Relatorio" sheetId="1" r:id="rId1"/></sheets></workbook>','xl/_rels/workbook.xml.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>', 'xl/worksheets/sheet1.xml':sheet};const out=zipStore(files);res.writeHead(200,{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':'attachment; filename="rbs-relatorio-v30.xlsx"'});res.end(out);return true}return json(res,400,{error:'Formato inválido',supported:['csv','xlsx','pdf']})}
 if(req.method==='POST'&&p==='/api/v30/report-runs'){const b=await body(req),x={id:id('REP'),type:clean(b.type)||'executivo',format:clean(b.format)||'csv',createdAt:new Date().toISOString()};db.reportRuns.unshift(x);save();return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/v30/report-runs')return json(res,200,db.reportRuns);
 return false;
}
module.exports={init,handle};
