const crypto=require('crypto');
const id=p=>p+'-'+crypto.randomBytes(5).toString('hex').toUpperCase();
const clean=s=>String(s??'').trim().slice(0,5000);
function init(db){
 const keys=['supplierContacts','purchasePlans','stockLots','stockCounts','posSales','posItems','quoteTemplates','projects','projectTasks','projectCosts','serviceOrders','serviceTasks'];
 for(const k of keys)if(!Array.isArray(db[k]))db[k]=[];
}
function money(v){const n=Number(v);return Number.isFinite(n)&&n>=0?n:0}
function auth(req){return !!req._rbsSession}
async function handle(req,res,ctx){
 const {db,save,json,body,session}=ctx; req._rbsSession=session(req); if(!auth(req)) return false;
 const p=new URL(req.url,'http://localhost').pathname;
 // V20 Fornecedores e Compras Avançadas
 if(req.method==='GET'&&p==='/api/v20/suppliers/summary'){return json(res,200,{suppliers:db.suppliers.length,active:db.suppliers.filter(x=>x.status!=='Inativo').length,contacts:db.supplierContacts.length,purchasePlans:db.purchasePlans.length,totalPlanned:db.purchasePlans.reduce((n,x)=>n+money(x.total),0)})}
 if(req.method==='POST'&&p==='/api/v20/supplier-contacts'){const b=await body(req);if(!clean(b.supplierId)||!clean(b.type)||!clean(b.note))return json(res,400,{error:'Fornecedor, tipo e nota são obrigatórios'});const x={id:id('FCT'),supplierId:clean(b.supplierId),type:clean(b.type),note:clean(b.note),date:clean(b.date)||new Date().toISOString(),createdAt:new Date().toISOString()};db.supplierContacts.unshift(x);save();return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/v20/supplier-contacts'){return json(res,200,db.supplierContacts)}
 if(req.method==='POST'&&p==='/api/v20/purchase-plans'){const b=await body(req);const items=Array.isArray(b.items)?b.items.slice(0,100):[];if(!items.length)return json(res,400,{error:'Itens obrigatórios'});const total=items.reduce((n,x)=>n+money(x.quantity)*money(x.unitPrice),0);const x={id:id('PPL'),supplierId:clean(b.supplierId),items,total,status:clean(b.status)||'Planeada',expectedDate:clean(b.expectedDate),notes:clean(b.notes),createdAt:new Date().toISOString()};db.purchasePlans.unshift(x);save();return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/v20/purchase-plans'){return json(res,200,db.purchasePlans)}
 // V21 Stock profissional
 if(req.method==='GET'&&p==='/api/v21/stock/summary'){const products=db.products;return json(res,200,{products:products.length,totalUnits:products.reduce((n,x)=>n+money(x.stock),0),lowStock:products.filter(x=>money(x.stock)<=5&&x.status!=='Inativo').length,stockValue:products.reduce((n,x)=>n+money(x.stock)*money(String(x.price).replace(/[^0-9.,]/g,'').replace(',','.')),0),lots:db.stockLots.length,counts:db.stockCounts.length})}
 if(req.method==='POST'&&p==='/api/v21/stock/lots'){const b=await body(req);if(!clean(b.productId)||!clean(b.lot)||money(b.quantity)<=0)return json(res,400,{error:'Produto, lote e quantidade válidos são obrigatórios'});const x={id:id('LOT'),productId:clean(b.productId),lot:clean(b.lot),quantity:money(b.quantity),expiryDate:clean(b.expiryDate),location:clean(b.location),createdAt:new Date().toISOString()};db.stockLots.unshift(x);save();return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/v21/stock/lots'){return json(res,200,db.stockLots)}
 if(req.method==='POST'&&p==='/api/v21/stock/counts'){const b=await body(req);const items=Array.isArray(b.items)?b.items:[];if(!items.length)return json(res,400,{error:'Itens da contagem obrigatórios'});const x={id:id('CNT'),areaCode:clean(b.areaCode),location:clean(b.location),items,notes:clean(b.notes),status:clean(b.status)||'Aberta',createdAt:new Date().toISOString()};db.stockCounts.unshift(x);save();return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/v21/stock/counts'){return json(res,200,db.stockCounts)}
 // V22 POS
 if(req.method==='GET'&&p==='/api/v22/pos/summary'){const sales=db.posSales;return json(res,200,{sales:sales.length,revenue:sales.reduce((n,x)=>n+money(x.total),0),paid:sales.reduce((n,x)=>n+money(x.paidAmount),0),pending:sales.reduce((n,x)=>n+Math.max(0,money(x.total)-money(x.paidAmount)),0)})}
 if(req.method==='POST'&&p==='/api/v22/pos/sales'){const b=await body(req),items=Array.isArray(b.items)?b.items.slice(0,100):[];if(!items.length)return json(res,400,{error:'Itens obrigatórios'});const total=items.reduce((n,x)=>n+money(x.quantity)*money(x.unitPrice),0);for(const it of items){const p=db.products.find(q=>q.id===clean(it.productId));if(!p)return json(res,400,{error:'Produto não encontrado'});if(money(p.stock)<money(it.quantity))return json(res,400,{error:'Stock insuficiente para '+p.name})}for(const it of items){const p=db.products.find(q=>q.id===clean(it.productId));p.stock-=money(it.quantity)}const x={id:id('POS'),customerId:clean(b.customerId),items,total,paidAmount:money(b.paidAmount),paymentMethod:clean(b.paymentMethod)||'Numerário',status:'Concluída',createdAt:new Date().toISOString()};db.posSales.unshift(x);db.cashMovements.unshift({id:id('CX'),type:'Entrada',description:'Venda POS '+x.id,amount:x.paidAmount,reference:x.id,createdAt:x.createdAt});save();return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/v22/pos/sales'){return json(res,200,db.posSales)}
 // V23 Orçamentos profissionais
 if(req.method==='GET'&&p==='/api/v23/quotes/summary'){return json(res,200,{quotes:db.quotes.length,total:db.quotes.reduce((n,x)=>n+money(x.total),0),approved:db.quotes.filter(x=>x.status==='Aprovado').length,pending:db.quotes.filter(x=>!['Aprovado','Cancelado'].includes(x.status)).length})}
 if(req.method==='POST'&&p==='/api/v23/quotes'){const b=await body(req),items=Array.isArray(b.items)?b.items:[];if(!clean(b.customerId)||!items.length)return json(res,400,{error:'Cliente e itens são obrigatórios'});const total=items.reduce((n,x)=>n+money(x.quantity)*money(x.unitPrice),0);const x={id:id('ORC'),number:'ORC/'+new Date().getFullYear()+'/'+String(db.quotes.length+1).padStart(5,'0'),customerId:clean(b.customerId),validUntil:clean(b.validUntil),items,subtotal:total,discount:money(b.discount),tax:money(b.tax),total:Math.max(0,total-money(b.discount)+money(b.tax)),status:'Rascunho',notes:clean(b.notes),createdAt:new Date().toISOString()};db.quotes.unshift(x);save();return json(res,201,x)}
 if(req.method==='PUT'&&p.startsWith('/api/v23/quotes/')){const k=p.split('/').pop(),x=db.quotes.find(q=>q.id===k);if(!x)return json(res,404,{error:'Orçamento não encontrado'});const b=await body(req);if(b.status&&!['Rascunho','Enviado','Aprovado','Rejeitado','Cancelado'].includes(b.status))return json(res,400,{error:'Estado inválido'});Object.assign(x,{status:clean(b.status)||x.status,notes:b.notes!==undefined?clean(b.notes):x.notes,validUntil:b.validUntil!==undefined?clean(b.validUntil):x.validUntil,updatedAt:new Date().toISOString()});save();return json(res,200,x)}
 if(req.method==='GET'&&p==='/api/v23/quotes'){return json(res,200,db.quotes)}
 // V24 Projetos e Obras
 if(req.method==='GET'&&p==='/api/v24/projects/summary'){return json(res,200,{projects:db.projects.length,active:db.projects.filter(x=>x.status==='Em execução').length,completed:db.projects.filter(x=>x.status==='Concluído').length,budget:db.projects.reduce((n,x)=>n+money(x.budget),0),costs:db.projectCosts.reduce((n,x)=>n+money(x.amount),0)})}
 if(req.method==='POST'&&p==='/api/v24/projects'){const b=await body(req);if(!clean(b.name))return json(res,400,{error:'Nome obrigatório'});const x={id:id('PROJ'),code:'PROJ-'+String(db.projects.length+1).padStart(5,'0'),name:clean(b.name),areaCode:clean(b.areaCode),customerId:clean(b.customerId),manager:clean(b.manager),startDate:clean(b.startDate),endDate:clean(b.endDate),budget:money(b.budget),status:clean(b.status)||'Planeado',description:clean(b.description),createdAt:new Date().toISOString()};db.projects.unshift(x);save();return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/v24/projects'){return json(res,200,db.projects)}
 if(req.method==='POST'&&p==='/api/v24/project-tasks'){const b=await body(req);if(!clean(b.projectId)||!clean(b.title))return json(res,400,{error:'Projeto e tarefa obrigatórios'});const x={id:id('PTK'),projectId:clean(b.projectId),title:clean(b.title),assignedTo:clean(b.assignedTo),dueDate:clean(b.dueDate),status:clean(b.status)||'Pendente',priority:clean(b.priority)||'Normal',createdAt:new Date().toISOString()};db.projectTasks.unshift(x);save();return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/v24/project-tasks'){return json(res,200,db.projectTasks)}
 if(req.method==='POST'&&p==='/api/v24/project-costs'){const b=await body(req);if(!clean(b.projectId)||money(b.amount)<=0)return json(res,400,{error:'Projeto e valor obrigatório'});const x={id:id('PCO'),projectId:clean(b.projectId),category:clean(b.category)||'Geral',description:clean(b.description),amount:money(b.amount),date:clean(b.date)||new Date().toISOString().slice(0,10),createdAt:new Date().toISOString()};db.projectCosts.unshift(x);save();return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/v24/project-costs'){return json(res,200,db.projectCosts)}
 // V25 Serviços técnicos
 if(req.method==='GET'&&p==='/api/v25/services/summary'){return json(res,200,{orders:db.serviceOrders.length,open:db.serviceOrders.filter(x=>!['Concluído','Cancelado'].includes(x.status)).length,completed:db.serviceOrders.filter(x=>x.status==='Concluído').length,value:db.serviceOrders.reduce((n,x)=>n+money(x.total),0),tasks:db.serviceTasks.length})}
 if(req.method==='POST'&&p==='/api/v25/service-orders'){const b=await body(req);if(!clean(b.customerId)||!clean(b.title))return json(res,400,{error:'Cliente e título são obrigatórios'});const x={id:id('OS'),number:'OS/'+new Date().getFullYear()+'/'+String(db.serviceOrders.length+1).padStart(5,'0'),customerId:clean(b.customerId),areaCode:clean(b.areaCode),title:clean(b.title),description:clean(b.description),technician:clean(b.technician),scheduledDate:clean(b.scheduledDate),priority:clean(b.priority)||'Normal',status:clean(b.status)||'Aberto',total:money(b.total),createdAt:new Date().toISOString()};db.serviceOrders.unshift(x);save();return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/v25/service-orders'){return json(res,200,db.serviceOrders)}
 if(req.method==='PUT'&&p.startsWith('/api/v25/service-orders/')){const k=p.split('/').pop(),x=db.serviceOrders.find(q=>q.id===k);if(!x)return json(res,404,{error:'Ordem não encontrada'});const b=await body(req);if(b.status&&!['Aberto','Agendado','Em execução','Concluído','Cancelado'].includes(b.status))return json(res,400,{error:'Estado inválido'});for(const f of ['status','technician','scheduledDate','description','priority'])if(b[f]!==undefined)x[f]=clean(b[f]);if(b.total!==undefined)x.total=money(b.total);x.updatedAt=new Date().toISOString();save();return json(res,200,x)}
 if(req.method==='POST'&&p==='/api/v25/service-tasks'){const b=await body(req);if(!clean(b.serviceOrderId)||!clean(b.title))return json(res,400,{error:'Ordem e tarefa obrigatórias'});const x={id:id('STK'),serviceOrderId:clean(b.serviceOrderId),title:clean(b.title),assignedTo:clean(b.assignedTo),status:clean(b.status)||'Pendente',dueDate:clean(b.dueDate),createdAt:new Date().toISOString()};db.serviceTasks.unshift(x);save();return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/v25/service-tasks'){return json(res,200,db.serviceTasks)}
 return false;
}
module.exports={init,handle};
