const fs=require('fs');
const p='/mnt/data/rbs_v13/rbs_v12/server.js';
let s=fs.readFileSync(p,'utf8');
s=s.replace("for(const k of ['products','orders','users','customers','quotes','stockMovements'])", "for(const k of ['products','orders','users','customers','quotes','stockMovements','suppliers','purchases','sales','expenses','cashMovements'])");
s=s.replace("CREATE TABLE IF NOT EXISTS stock_movements", "CREATE TABLE IF NOT EXISTS suppliers(id text primary key,name text not null,phone text,email text,company text,note text,created_at timestamptz default now());CREATE TABLE IF NOT EXISTS purchases(id text primary key,supplier_id text,items jsonb not null default '[]',total numeric default 0,status text not null,created_at timestamptz default now());CREATE TABLE IF NOT EXISTS sales(id text primary key,customer_id text,items jsonb not null default '[]',total numeric default 0,status text not null,created_at timestamptz default now());CREATE TABLE IF NOT EXISTS expenses(id text primary key,description text not null,category text,amount numeric not null,created_at timestamptz default now());CREATE TABLE IF NOT EXISTS cash_movements(id text primary key,type text not null,description text,amount numeric not null,reference text,created_at timestamptz default now());CREATE TABLE IF NOT EXISTS stock_movements");
const marker=" if(req.method==='GET'&&p==='/api/dashboard')";
const insert=`
 if(req.method==='GET'&&p==='/api/suppliers'){if(!auth(req))return json(res,401,{error:'Não autorizado'});if(pool){const r=await pool.query('SELECT id,name,phone,email,company,note,created_at "createdAt" FROM suppliers ORDER BY created_at DESC');return json(res,200,r.rows)}return json(res,200,db.suppliers)}
 if(req.method==='POST'&&p==='/api/suppliers'){if(!auth(req))return json(res,401,{error:'Não autorizado'});const b=await body(req);if(!clean(b.name)||!clean(b.phone))return json(res,400,{error:'Nome e telefone são obrigatórios'});const x={id:id('FOR'),name:clean(b.name),phone:clean(b.phone),email:clean(b.email),company:clean(b.company),note:clean(b.note),createdAt:new Date().toISOString()};if(pool)await pool.query('INSERT INTO suppliers(id,name,phone,email,company,note,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[x.id,x.name,x.phone,x.email,x.company,x.note,x.createdAt]);else{db.suppliers.unshift(x);save()}return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/purchases'){if(!auth(req))return json(res,401,{error:'Não autorizado'});if(pool){const r=await pool.query('SELECT id,supplier_id "supplierId",items,total,status,created_at "createdAt" FROM purchases ORDER BY created_at DESC');return json(res,200,r.rows.map(x=>({...x,items:typeof x.items==='string'?JSON.parse(x.items):x.items})))}return json(res,200,db.purchases)}
 if(req.method==='POST'&&p==='/api/purchases'){if(!auth(req))return json(res,401,{error:'Não autorizado'});const b=await body(req);const x={id:id('CMP'),supplierId:clean(b.supplierId),items:Array.isArray(b.items)?b.items.slice(0,100):[],total:Number(b.total||0),status:clean(b.status)||'Recebida',createdAt:new Date().toISOString()};if(pool)await pool.query('INSERT INTO purchases(id,supplier_id,items,total,status,created_at) VALUES($1,$2,$3,$4,$5,$6)',[x.id,x.supplierId,JSON.stringify(x.items),x.total,x.status,x.createdAt]);else{db.purchases.unshift(x);save()}return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/sales'){if(!auth(req))return json(res,401,{error:'Não autorizado'});if(pool){const r=await pool.query('SELECT id,customer_id "customerId",items,total,status,created_at "createdAt" FROM sales ORDER BY created_at DESC');return json(res,200,r.rows.map(x=>({...x,items:typeof x.items==='string'?JSON.parse(x.items):x.items})))}return json(res,200,db.sales)}
 if(req.method==='POST'&&p==='/api/sales'){if(!auth(req))return json(res,401,{error:'Não autorizado'});const b=await body(req);const x={id:id('VEN'),customerId:clean(b.customerId),items:Array.isArray(b.items)?b.items.slice(0,100):[],total:Number(b.total||0),status:clean(b.status)||'Concluída',createdAt:new Date().toISOString()};if(pool)await pool.query('INSERT INTO sales(id,customer_id,items,total,status,created_at) VALUES($1,$2,$3,$4,$5,$6)',[x.id,x.customerId,JSON.stringify(x.items),x.total,x.status,x.createdAt]);else{db.sales.unshift(x);save()}return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/expenses'){if(!auth(req))return json(res,401,{error:'Não autorizado'});if(pool){const r=await pool.query('SELECT id,description,category,amount,created_at "createdAt" FROM expenses ORDER BY created_at DESC');return json(res,200,r.rows)}return json(res,200,db.expenses)}
 if(req.method==='POST'&&p==='/api/expenses'){if(!auth(req))return json(res,401,{error:'Não autorizado'});const b=await body(req);const amount=Number(b.amount);if(!clean(b.description)||!Number.isFinite(amount)||amount<=0)return json(res,400,{error:'Descrição e valor positivo são obrigatórios'});const x={id:id('DES'),description:clean(b.description),category:clean(b.category)||'Geral',amount,createdAt:new Date().toISOString()};if(pool)await pool.query('INSERT INTO expenses(id,description,category,amount,created_at) VALUES($1,$2,$3,$4,$5)',[x.id,x.description,x.category,x.amount,x.createdAt]);else{db.expenses.unshift(x);save()}return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/cash'){if(!auth(req))return json(res,401,{error:'Não autorizado'});if(pool){const r=await pool.query('SELECT id,type,description,amount,reference,created_at "createdAt" FROM cash_movements ORDER BY created_at DESC');return json(res,200,r.rows)}return json(res,200,db.cashMovements)}
 if(req.method==='POST'&&p==='/api/cash'){if(!auth(req))return json(res,401,{error:'Não autorizado'});const b=await body(req);const amount=Number(b.amount);if(!['Entrada','Saída'].includes(b.type)||!Number.isFinite(amount)||amount<=0)return json(res,400,{error:'Tipo e valor positivo são obrigatórios'});const x={id:id('CX'),type:b.type,description:clean(b.description),amount,reference:clean(b.reference),createdAt:new Date().toISOString()};if(pool)await pool.query('INSERT INTO cash_movements(id,type,description,amount,reference,created_at) VALUES($1,$2,$3,$4,$5,$6)',[x.id,x.type,x.description,x.amount,x.reference,x.createdAt]);else{db.cashMovements.unshift(x);save()}return json(res,201,x)}
 if(req.method==='GET'&&p==='/api/reports'){if(!auth(req))return json(res,401,{error:'Não autorizado'});const [ps,os,cs,qs]=await Promise.all([productsAll(),ordersAll(),customersAll(),quotesAll()]);let suppliers=[],purchases=[],sales=[],expenses=[],cash=[];if(pool){const [a,b,c,d,e]=await Promise.all([pool.query('SELECT * FROM suppliers'),pool.query('SELECT total,status FROM purchases'),pool.query('SELECT total,status FROM sales'),pool.query('SELECT amount FROM expenses'),pool.query('SELECT type,amount FROM cash_movements')]);suppliers=a.rows;purchases=b.rows;sales=c.rows;expenses=d.rows;cash=e.rows}else{({suppliers,purchases,sales,expenses,cashMovements:cash}=db)}const sum=a=>a.reduce((n,x)=>n+Number(x.total||x.amount||0),0);return json(res,200,{customers:cs.length,suppliers:suppliers.length,products:ps.length,orders:os.length,quotes:qs.length,purchases:purchases.length,sales:sales.length,expenses:expenses.length,revenue:sum(sales),purchasesValue:sum(purchases),expensesValue:sum(expenses),cashIn:sum(cash.filter(x=>x.type==='Entrada')),cashOut:sum(cash.filter(x=>x.type==='Saída')),stockValue:ps.reduce((n,x)=>n+(Number(x.stock)||0)*(Number(String(x.price||'').replace(/[^0-9.,]/g,'').replace(',','.'))||0),0)});}
`;
s=s.replace(marker,insert+marker);
s=s.replace("version:'12.0.0'","version:'13.0.0'").replace("console.log(`RBS V11: http://localhost:${PORT}`)","console.log(`RBS V13: http://localhost:${PORT}`)");
fs.writeFileSync(p,s);
